### ISSUE TITLE
Inkonsekvent setningsform for sjekkliste for stadium 4

### ISSUE THREAD

**Issue by huftis** [Rapporteket/RARTemplate#6]
Sjekklista for stadium 4 er:

    16 Kan dokumentere registerets datakvalitet gjennom valideringsanalyser
    17 Presenterer oppdatert dekningsgradsanalyse hvert 2. år
    18 Har dekningsgrad over 80%
    19 Registrerende enheter har løpende (on-line) tilgang til oppdaterte egne og nasjonale resultater
    20 Kunne dokumentere at registeret har ført til kvalitetsforbedring/endret klinisk praksis

Alle punkta er skrivne i presensform («kan», «presenterer», «har») (og dette gjeld òg punkta i stadium 2 og 3), men siste punkt har ei heilt anna setningsform («kunne»). Dette er forvirrande/forstyrrande.

Ordet «Kunne» i sjekkpunkt 20 bør derfor bytast ut med ordet «Kan».

**Comment by areedv** [comment]
Takk, og helt enig.
